@startuml


class User
class Post
class Profile
class Media
class Tag
class Like
class Comment
class Follower


class User {
    +username:str
    -email:str
    -password:str
    register_user()
    confirm_registration_email()
    add_profile_info()
    create_post()
    like_post()
    comment_post()
    follow_profile()
}

class Post {
    +author:User
    +description:str
    #add_image()
    #add_tag()
    #edit_description()
    +add_like()
    +add_comment()
}

class Profile {
    +full_name:str
    +bio:str
    +avatar:image
    #edit_profile()
}

class Tag {
    +title:str
}

class Like {
    +liker:User
    +target:Post
}

class Media {
    image:path
}

class Comment {
    +author:User
    +text:str
    +target:Post
}

class Follower {
    +follower: User
    +target: Profile
}


User "1" *- "many" Post : creating >
User "1" *- "1" Profile
User "1"-->"many" Like
User "1"-->"many" Comment
Profile "1" --> "many" Post : contains >
Post --|> User
Post "1"-->"many" Media
Post "1"-->"many" Tag
Post "1"-->"many" Comment
Post "1"-->"many" Like
Tag "1" o-- "many" Post
Follower "many"<-->"many" Profile
Follower <-- User



@enduml
