# Generated by Django 4.2.1 on 2023-05-15 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
