# Generated by Django 4.2.1 on 2023-05-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogramm', '0002_alter_customuser_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target',
            new_name='target_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='target_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='djangogramm.comment'),
            preserve_default=False,
        ),
    ]
